language: java
addons:
  sonarcloud:
    organization: "dmitriy-g"
    token:
      secure: "F1wm56z4UXbR3cEDeuN5BL9MJCA0T4b1mxKl5lWOQYRKjM1u+GEcmBkmX+V/7eTuhyEkIGo8mqQAN8qGTYpfhzPOWuH2M2HXd3OzZulQqWEkUfSd5DRKqh+F/KRQ0ikJX0eonzyU9eYTmf7LQdpdVweQVX8MkxeGrgMW33Nt1wPoRnplU12Bdr4mpmFmYIuzPI3XEWmKPmjSmTuoBrs9tsdLNEn27HpEbfUV0P6ctlKH5Txq7NxgR8jX4xp6i1IOf0gEVgYh77Px10bdvHpJhn04k4cXQqbXJIEcaGjAYwKX6u30YCkV461gwVeiTi/UddgTQ+rcER1oxWSB14aA5MY5Pb+dIPqS36n+Z4espT0aBn/Ow5zzXqJluB3O/vOgvBhECN8Tbt5piuufffnJqn/28FvkBM7xepNQPw+fHepsaBLRhAfaq0R3gpc7sicMt4CQQzBERiGj2n/h5IiIO3nNBfQigSqZsw6sjmCU+gTOF/4vs0ulOdA1L9hy4OOk2YRW7DlrqMB4Ns64gbUpFII9om/DJORsDnAqqgslw+fJ3nyXBb6Iu/T3PLdS6GYrZ/peTA4LJjpU1T88rCdXd6uDYHPmmyZAiJhG2gxfdG7BslO9yHQNim0bIKB8/j5ILV+5afcc616ApZGZhMBaTkXPR4RdQJNv33wdPFKzSZ8=" # encrypted value of your token
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Dmitriy-G_vacancy-aggregator-micro
after_success:
  - bash <(curl -s https://codecov.io/bash)