language: java
addons:
  sonarcloud:
    organization: "dmitriy-g"
    token: ${{ secrets.SONAR_TOKEN }}
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Dmitriy-G_vacancy-aggregator-micro -Dsonar.exclusions=**/*.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)