language: java
addons:
  sonarcloud:
    organization: "dmitriy-g"
    token: "ZZ8bEry84mpPfKkziqs3+L6DmbF2AM0DXxZILqQcDd8kswu6iMirH3KbUegpw+DZKxJjxSaxLIEU/kbv+m1/gatDWBLi179lH1eW/v4dUEWlTwmA4GGRppc5f4Lp5XoLKnnFuWfhV29ycT1AowK11i13Z/chXY9JWKdvwTnBHrIUvqrzx5OJYxfbIQsMJMakUZ/MdzTWXcVdFuvR/cZ0uuKV5pxZCYaqcHxH9DdDE1SPi3Myvhhh4anFwZvyo5T3Fx6CtXc4HU66j35cvsrkFXE9HjaBYU8rRuxBSKrySEeB5r9IT2BuV0O0ufp650u81rMNlwA5MayhPCpVMifetlJkppzTkLtt4e27FJcUAOOExo65KkC+eRTMJl3uCo1UCxRQwwfhpJ4PmhqTlZQYlAYW5CDC+Ah5WzE+6T8skNNolRTX70eG68CxakpaGHk8u4Uhisdn7/ozBAgC78Dqs9IYZm5CWlTbm+1ZCXmMWsqfcdkG+jEpIAHvibxuZhR9eIWIw3MGUvxeqnG3N0oQR5PvHZWUSDyTcT1q+NNh526Y/wJgL4VmHimJV86JZmAlharv0pYEZEWoI5FLQWwvjlSpWIbRzaJinyg73rf+W6r5PhreC4RCIwGemDWBHMBoW+b6ReEWTEh8VhVjYry69k4GtA7xEvZnU0d2lXoW9fg="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Dmitriy-G_vacancy-aggregator-micro -Dsonar.exclusions=**/*.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)