language: java
addons:
  sonarcloud:
    organization: "dmitriy-g"
    token:
      secure: "AEbYbcDfuX0kMkU2L+dJSJWCsKoZ3KX9vZdInV4YfOvUvsMdRwEBa7kYzLk4sIOBfmh72vfhfu5XP8SBXp4+AjUrllV52RvyyXz7oR90N5CPkM6tBpOhPnkY9ANkpcrRYTcEpWpdyMMcEI6XPhWsWEOHfCZqKSy5XcnPynkQqFCJf+NoOgamlcRpAHnHSp/iOQA7GNQOXws2Ur1lr3yH0pQKk/G7C4pXjsyJtU5gwsdDvsqVQT2pUnwyHpje4AtmQMUXrnwxwrGzSIfKqmTLa+z5+Xzh85ncy4qdfiv37zA3eCEzNZqo8TKMPimhlar6gnW7XgMWGSoYZoVnSkksYB/OkNP8s84BVlFcCt+2tgSrJHDJkOv4LFLXh1uNDV2Dft4xVyH666FYs7r7v5tXJm6Dz4T9IdZAkq87b+OVO+xlRUlMWrVKp2LYIhA9tJO8HsvA2d0CLuXlpmp349fQPx9v3gRKe12g9dmAWBcetLzlDd+HykE6+DtBJxlPLm/wIROTtb6bHct/ZYkS82Hd2GFfX9C7ddIplD6Uf3oA9fn/fi3dV3evc+gzd0xD8b+OH9sc8RHwBl7zEDRFb/H0d0AhOwJzr4jv/Lwa/7c5ts7kIa2gDnuuHngnQlyJK42AvAaq39QYfbmEjOGiEsRGh+aLvywSY90UrI8VR7CucTA="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Dmitriy-G_vacancy-aggregator-micro -Dsonar.exclusions=**/*.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)