language: java
addons:
  sonarcloud:
    organization: "dmitriy-g"
    token:
      secure: "vrvtJr1wvewZmJQ2KEmz+e45VAZNEzZXaWWnBbfsYKiaFqjPyUlMehp8LmFX4rnjJTWqjItOlyPGZwktHjSayAQR1YaPDolSCTlXzO2YEc42UORuBNLdb6NdzpjIc7vGjmRk4keMkz0tjev85YGdFxFgA/1Lnnx4CV/HIr1T2lKAtcUQPGtpxh04bsayaUTUymDn4nr+3gnDtueW9yv5cLizZJL6pnB/F9qIQ4ZCllCZ6hE/axRM6TNNYf30KpfzMep6FGvPnZEq8Fb+8VoHYOn69jBua0xSqjD6JlGQ2fWBugM4CwYGUlBTL9M1fmj6HmXtssUkTWjy0cStSggbIvJDRpir3TCDMeqXM3fkIYcD3Sui39+f2Ui1FiGcJ6RMCTchA4NVVcpdB1/j9hF8JuJS9oDpd4Fg11ayClCdqHjpxQIrP4w1RPzs/7NKq1I378GRxwY8pK9JiJyHhyX9Qa6KpgrogEzGBP7MDCWNNGe6QmoBJKL16+7Jic3jFqrGSxJANSvASBWLNlY4ubv8CWvfCxZUzRkgP5Xo56c1vfflKkcQtHG3TUJImueE0JlVtIqj47daA5RIROHZsjrIPbSFpMNmBaNPaKbpGpjlhWh/58ushuzfHTYF/g1s5F7NyhL/tcnWu+IQttn43tpiQq+1uWaUblsewwMqCBy8Jso="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Dmitriy-G_vacancy-aggregator-micro -Dsonar.exclusions=**/*.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)