version: '2.2'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 15s
      retries: 10
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: customerManagerService
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
  vacancy_aggregator_core:
    build: vacancy_aggregator_core
    ports:
      - "8010:8010"
    environment:
      APP_MQ_HOST: rabbitmq
      APP_MQ_USER: guest
      APP_MQ_PASSWORD: guest
    depends_on:
      rabbitmq:
        condition: service_healthy
  notification-sender:
    build: notification_sender
    ports:
      - "8020:8020"
    environment:
      APP_MQ_HOST: rabbitmq
      APP_MQ_USER: guest
      APP_MQ_PASSWORD: guest
    depends_on:
      rabbitmq:
        condition: service_healthy