version: '2.2'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 15s
      retries: 10
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: customerManagerService
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-volume:/var/lib/mongo/data

  keycloakdb:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - keycloak-data-volume:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:11.0.2
    environment:
      DB_VENDOR: "POSTGRES"
      DB_ADDR: keycloakdb
      DB_PORT: 5432
      DB_USER: keycloak
      DB_PASSWORD: password
      #KEYCLOAK_USER: admin
      #KEYCLOAK_PASSWORD: password
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - keycloakdb

  vacancy_aggregator_core:
    build: vacancy_aggregator_core
    ports:
      - "8010:8010"
    environment:
      APP_MQ_HOST: rabbitmq
      APP_MQ_USER: guest
      APP_MQ_PASSWORD: guest
      NOTIFICATION_QUEUE_NAME: notification-queue
      NOTIFICATION_EXCHANGE: notification-exchange
      NOTIFICATION_ROUTING_KEY: notification-routing-key
    depends_on:
      rabbitmq:
        condition: service_healthy
  notification-sender:
    build: notification_sender
    ports:
      - "8020:8020"
    environment:
      APP_MQ_HOST: rabbitmq
      APP_MQ_USER: guest
      APP_MQ_PASSWORD: guest
      NOTIFICATION_QUEUE_NAME: notification-queue
      NOTIFICATION_EXCHANGE: notification-exchange
      NOTIFICATION_ROUTING_KEY: notification-routing-key
      TELEGRAM_BOT_NAME: java_position_sender_test_bot
      TELEGRAM_TOKEN: 1178890242:AAEqVpKs_fx8miC_QERngbhVM76wvApjwfg
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  keycloak-data-volume:
    external: true
  mongo-data-volume:
    external: true