rabbitmq:
  receiveQueueName: ${NOTIFICATION_QUEUE_NAME:notification-queue}
  receiveExchange: ${NOTIFICATION_EXCHANGE:notification-exchange}
  receiveRoutingKey: ${NOTIFICATION_ROUTING_KEY:notification-routing-key}

telegram:
  telegramBotName: ${TELEGRAM_BOT_NAME}
  telegramBotToken: ${TELEGRAM_TOKEN}
  type: Telegram

spring:
  rabbitmq:
    host: ${APP_MQ_HOST:localhost}
    username: ${APP_MQ_USER:guest}
    password: ${APP_MQ_PASSWORD:guest}