rabbitmq:
  queueName: ${NOTIFICATION_QUEUE_NAME:notification-queue}
  exchange: ${NOTIFICATION_EXCHANGE:notification-exchange}
  routingKey: ${NOTIFICATION_ROUTING_KEY:notification-routing-key}

spring:
  rabbitmq:
    host: ${APP_MQ_HOST:localhost}
    username: ${APP_MQ_USER:guest}
    password: ${APP_MQ_PASSWORD:guest}