rabbitmq:
  receiveQueueName: notification-queue
  receiveExchange: notification-exchange
  receiveRoutingKey: notification-routing-key

spring:
  rabbitmq:
    host: ${APP_MQ_HOST:localhost}
    username: ${APP_MQ_USER:guest}
    password: ${APP_MQ_PASSWORD:guest}